# Set base paths for templates
# and target files to be more concise.
base:
  templates: ./templates
  target: ./src

generators:
  entry:
    props:
      - name: name
        doc: Entry name

    files:
      - template: entry.hbs
        target: entries/{{ kebab-case name }}.md

  collection:
    props:
      - name: name
        doc: Collection name

    files:
      - template: collection.hbs
        target: collections/{{ kebab-case name }}.md
    prompt:
      - key: name
        doc: Collection name

  series:
    props:
      - name: name
        doc: Series name

    files:
      - template: series.hbs
        target: series/{{ kebab-case name }}.md
